# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-14 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantified_self', '0002_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='foods',
            field=models.ManyToManyField(to='quantified_self.Food'),
        ),
    ]
